baseURL = "https://EJ-Tether.github.io/relational-AI-world/"
languageCode = "fr-fr"
title = "Relational AI"
theme = "blowfish"

defaultContentLanguage = "en"


[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    title = "Accueil"
    [languages.fr.params]
      displayName = "FR"
      isoCode = "fr"
      rtl = false

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Home"
    [languages.en.params]
      displayName = "EN"
      isoCode = "en"
      rtl = false

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/:year/:month/:title/"
  authors = "/author/:slug/"

[params]
  colorScheme = "blowfish"
  defaultTheme = "light"
  enableSearch = true
  
  # Blowfish specific
  [params.header]
    layout = "basic" 
  
  [params.footer]
    showCopyright = true

  [params.homepage]
    layout = "background" # or "hero", "profile", etc.
    showRecent = true
    showSummary = true


